# to run the terminal in interactive mode:  docker-compose -f c:/docker/ALINEA/docker-compose.yml --env-file ./config.env run ALINEA bin/bash
services:
  ALINEA:
    build:
      dockerfile: Dockerfile
    image: img_alinea
    volumes: 
      - ${FOLDER_PATH}:/mnt/alinea_vol